//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLSAT257DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ActivityId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime DateTime { get; set; }
        public decimal Duration { get; set; }
        public int ActivityTypeId { get; set; }
        public string Details { get; set; }
        public int UserId { get; set; }
    
        public virtual ActivityType ActivityType { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual User User { get; set; }
    }
}
