//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLSAT257DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Activities = new HashSet<Activity>();
        }
    
        public int UserId { get; set; }
        public string Username { get; set; }
        public string DisplayName { get; set; }
    
        public virtual ICollection<Activity> Activities { get; set; }
    }
}
